# LLM Configuration
# LLM Configuration
model:
  host: "https://yf-personal-swedencentral.cognitiveservices.azure.com/"
  model: "GPT_4O"
  temperature: 0.7
  provider: "AZURE_OPENAI"
  apiKey: "Cb2lmbpN6LyQKj9FCwfbl9Oiv4rp5MztAvtCfPKrcMUvjREINMvRJQQJ99BJACfhMk5XJ3w3AAAAACOGnbkJ"
  apiVersion: "2024-12-01-preview"